name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore CloudGames.Payments.sln
      - name: Build
        run: dotnet build CloudGames.Payments.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test tests/CloudGames.Payments.Tests/CloudGames.Payments.Tests.csproj --no-build --configuration Release
      - name: Publish Web
        run: dotnet publish CloudGames.Payments.Web/CloudGames.Payments.Web.csproj -c Release -o ${{ github.workspace }}/artifacts/web
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ${{ github.workspace }}/artifacts/web
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web
          path: web
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: web
